---
title: "Methods and Results"
author: "Blain Morin"
date: "6/2/2022"
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(lubridate)
library(readr)
library(plotly)
library(ggridges)
library(stargazer)
library(data.table) 
library(fixest) 
library(did)
library(broom)
library(haven)
library(readxl)
library(kableExtra)
library(data.table)

df = fread("ucr1980_2000.csv")

```


```{r}

### Declare treated states
treated_states = c("washington", "wisconsin", "rhode island", "texas", "idaho", "iowa",
                   "michigan", "minnesota",
                   "oregon")

### Here I group by year, state, and agency and
### calculate the total DUI
df.sum = df %>%
  group_by(year, state) %>%
  summarise(DUI_Total = sum(dui_tot_arrests),
            DUI_Total_White = sum(dui_tot_white),
            DUI_Total_Black = sum(dui_tot_black),
            Prop_Arrests_Black_DUI = DUI_Total_Black / DUI_Total,
            Prop_Arrests_White_DUI = DUI_Total_White / DUI_Total,
            Prop_Arrests_Other_DUI = (DUI_Total - DUI_Total_White - DUI_Total_Black) / DUI_Total,

            Poss_Cann_Total = sum(poss_cannabis_tot_arrests),
            Poss_Cann_White = sum(poss_cannabis_tot_white),
            Poss_Cann_Total_Black = sum(poss_cannabis_tot_black),

            Poss_Drug_Total = sum(poss_drug_total_tot_arrests),
            Poss_Drug_Total_Black = sum(poss_drug_total_tot_black),
            
            Total_Drug_Total = sum(total_drug_tot_arrests),
            Total_Drug_White = sum(total_drug_tot_white),
            Total_Drug_Black = sum(total_drug_tot_black),
            
            Drunkenness_Total = sum(drunkenness_tot_arrests),
            Drunkenness_White = sum(drunkenness_tot_white),
            Drunkenness_Black = sum(drunkenness_tot_black)
            
            
            ) %>%
  ungroup()


df.sum = df.sum %>%
  mutate(treatdate = ifelse(state == "rhode island", "July 1989", NA)) %>%
  mutate(treatdate = ifelse(state == "washington", "May 1988", treatdate)) %>%
  mutate(treatdate = ifelse(state == "wisconsin", "Aug 1991", treatdate)) %>%
  mutate(treatdate = ifelse(state == "texas", "June 1994", treatdate)) %>%
  mutate(treatdate = ifelse(state == "idaho", "June 1988", treatdate)) %>%
  mutate(treatdate = ifelse(state == "iowa", "May 1986", treatdate)) %>%
  mutate(treatdate = ifelse(state == "michigan", "Sep 1993", treatdate)) %>%
  mutate(treatdate = ifelse(state == "minnesota", "Aug 1994", treatdate)) %>%
  mutate(treatdate = ifelse(state == "oregon", "Sep 1987", treatdate)) %>%
  ### Although the month is declared above, we only use the treatyear
  mutate(treatdate = my(treatdate)) %>%
  mutate(treatyear = format(treatdate, format = "%Y"))

df.sum = df.sum %>%
  ### Make the time to treat column
  mutate(timetotreat = as.numeric(year) - as.numeric(treatyear)) %>%
  ### Make indicator for treated state
  mutate(treated = ifelse(state %in% treated_states, 1, 0)) %>%
  ### Make years discrete
  mutate(fyear = as.factor(year)) 


### These are some non-states that are dropped from the analysis
nonstate = c("canal zone", "guam", "69", "98", "99", "american samoa", "virgin islands", "puerto rico")

### This filters out the non-states
df2 = df.sum %>%
  filter(!state %in% nonstate)

### Attach state weights
### Read in the file
state_populations = read_excel("laws and population.xlsx")

### Select relevant columns
state_populations = state_populations %>%
  select(`state name`, year, `population (hundreds of thousands)`)

### Rename and clean some columns so that they will join to 
### our UCR and FARS data
state_populations = state_populations %>%
  rename(state = `state name`) %>%
  rename(population = `population (hundreds of thousands)`) %>%
  mutate(state = tolower(state))

df3 = df2 %>%
  left_join(state_populations) %>%
  drop_na(population) 

df3 = df3 %>%
  mutate(timetotreat = replace_na(df3$timetotreat, 0)) %>%
  mutate(post = ifelse(timetotreat > 0, 1, 0)) %>%
  rename(treated_alt = treated)

df3 = df3 %>%
  mutate(gname = replace_na(as.numeric(df3$treatyear), 0)) %>%
  mutate(id.numeric = as.numeric(as.factor(state))) %>%
  filter(DUI_Total > 0)

countypop = read_dta("countypopagerace_19692017.dta")

statepops = countypop %>%
  filter(year %in% 1980:2000) %>%
  group_by(year, stfips, race) %>%
  summarise(population = sum(population))

state.id = read_csv("accident.CSV") %>% # Read in csv
  select(STATE, STATENAME) %>% # then select state id and state name columns
  group_by(STATENAME) %>% # then group by state
  slice(1) %>% # then grab one observation
  mutate(STATENAME = tolower(STATENAME)) %>% # then make the state names lowercase
  rename(state = STATE) 

fips.appendage = state.id %>%
  rename(stfips = state) %>%
  rename(state = STATENAME)

statepops = statepops %>%
  left_join(fips.appendage)

statepops = statepops %>%
  spread(race, population) %>%
  rename(white_pop = "1") %>%
  rename(black_pop = "2") %>%
  rename(other_pop = "3")

df4 = df3 %>%
  left_join(statepops) %>%
  mutate(population_nom = population * 1000) %>%
  mutate(dui_rate = DUI_Total / population_nom) %>%
  mutate(white_dui_rate = DUI_Total_White / white_pop) %>%
  mutate(black_dui_rate = DUI_Total_Black / black_pop) %>%
  mutate(Total_Other_DUI = DUI_Total - DUI_Total_White - DUI_Total_Black) %>%
  mutate(other_dui_rate = Total_Other_DUI / other_pop) %>%
  mutate(total_drug_rate = Total_Drug_Total / population_nom) %>%
  mutate(white_drug_rate = Total_Drug_White / white_pop) %>%
  mutate(black_drug_rate = Total_Drug_Black / black_pop) %>%
  mutate(Total_Other_Drug = Total_Drug_Total - Total_Drug_White - Total_Drug_Black) %>%
  mutate(other_drug_rate = Total_Other_Drug / other_pop) %>%
  mutate(Total_Poss_Cann_Rate = Poss_Cann_Total / population_nom) %>%
  mutate(white_cann_rate = Poss_Cann_White / white_pop) %>%
  mutate(black_cann_rate = Poss_Cann_Total_Black / black_pop) %>%
  mutate(Other_Poss_Cann = Poss_Cann_Total - Poss_Cann_White - Poss_Cann_Total_Black) %>%
  mutate(other_cann_rate = Other_Poss_Cann / other_pop) %>%
  mutate(drunkenness_rate = Drunkenness_Total / population_nom) %>%
  mutate(white_drunkenness_rate = Drunkenness_White / white_pop) %>%
  mutate(black_drunkenness_rate = Drunkenness_Black / black_pop) %>%
  mutate(Other_Drunkenness = Drunkenness_Total - Drunkenness_White - Drunkenness_Black) %>%
  mutate(other_drunkenness_rate = Other_Drunkenness / other_pop)



```


```{r}

fars = fread("state.fars.1980.2000.csv")

state_unemployment = read_excel("state_unemployment.xls", 
    sheet = "States", skip = 5)

state_unemployment = state_unemployment[2:52,]

state_unemployment = state_unemployment %>%
  filter(Area != "District of Columbia") %>%
  select(-Fips)

state_unemployment = state_unemployment[,1:22]

state_unemployment = state_unemployment %>%
  gather(key = "year", "unemp_rate", "1980":"2000")

state_unemployment = state_unemployment %>%
  mutate(Area = tolower(Area)) %>%
  rename(state = "Area") %>%
  mutate(year = as.integer(year))


#########################
#### Age 65 and older
#########################

statepop = countypop %>%
  filter(year %in% 1980:2000) %>%
  group_by(year, stfips) %>%
  summarise(populationtot = sum(population))

statepop2 = countypop %>%
  filter(year %in% 1980:2000) %>%
  filter(age >= 14) %>%
  group_by(year, stfips) %>%
  summarise(population = sum(population))

temp = statepop2 %>%
  left_join(statepop) %>%
  mutate(old65 = population / populationtot)

state.id = read_csv("accident.CSV") %>% # Read in csv
  select(STATE, STATENAME) %>% # then select state id and state name columns
  group_by(STATENAME) %>% # then group by state
  slice(1) %>% # then grab one observation
  mutate(STATENAME = tolower(STATENAME)) %>% # then make the state names lowercase
  rename(state = STATE) 

fips.appendage = state.id %>%
  rename(stfips = state) %>%
  rename(state = STATENAME)

temp65 = temp %>%
  left_join(fips.appendage)

state_per_cap_income = read_csv("state_per_cap_income.csv", 
    skip = 4)

state_per_cap_income = state_per_cap_income[2:52, -1]

state_per_cap_income = state_per_cap_income %>%
  mutate(GeoName = str_replace(GeoName, '\\*', '')) %>%
  mutate(GeoName = str_replace(GeoName, "Hawaii ", 'Hawaii')) %>%
  mutate(GeoName = str_replace(GeoName, "Alaska ", 'Alaska')) %>%
  mutate(GeoName = tolower(GeoName)) %>%
  rename(state = GeoName) %>%
  filter(state != "district of columbia") %>%
  gather(key = "year", value = "per_cap_income", "1980":"2000") %>%
  mutate(year = as.integer(year))


  

fars = fars %>%
  filter(state != "district of columbia") %>%
  left_join(state_unemployment) %>%
  left_join(state_per_cap_income) %>%
  left_join(temp65) %>%
  mutate(old65 = old65*100)

ucr.sum = df4 %>%
  group_by(treated_alt) %>%
  summarise(ave_duis = formatC(mean(DUI_Total), format = "f", digits = 2),
            sd_dui = sd(DUI_Total),
            ave_white_dui_rate = formatC(mean(white_dui_rate * 100), format = "f", digits = 4),
            sd_white_dui_rate = sd(white_dui_rate * 100, na.rm = T),
            ave_black_dui_rate = formatC(mean(black_dui_rate * 100), format = "f", digits = 4),
            sd_black_dui_rate = sd(black_dui_rate * 100, na.rm = T))

fars.sum = fars %>%
  rename(treated_alt = treated) %>%
  group_by(treated_alt) %>%
  summarise(ave_n_crashes = formatC(mean(n_crashes), format = "f", digits = 2),
            sd_n_crashes = sd(n_crashes),
            ave_n_fatals = formatC(mean(n_fatalities), format = "f", digits = 2),
            sd_n_fatal = sd(n_fatalities),
            ave_unemp_rate = formatC(mean(unemp_rate), format = "f", digits = 2),
            sd_unemp_rate = sd(unemp_rate),
            ave_per_cap_income = formatC(mean(per_cap_income), format = "f", digits = 2),
            sd_per_cap_income = sd(per_cap_income),
            ave_old_65 = formatC(mean(old65), format = "f", digits = 2),
            sd_old_65 = sd(old65))

sum.df = cbind(ucr.sum, fars.sum)

sum.df = sum.df[,-8]

sum.dft = as.data.frame(t(sum.df))

sum.dft = sum.dft[-1,]

thedf = data.frame(
  
  Variable = rownames(sum.dft),
  control = sum.dft$V1,
  treat = sum.dft$V2
  
)

thedf = thedf %>%
  rename("Control States" = control) %>%
  rename("Treated States" = treat)

thedf = thedf %>%
  filter(grepl("ave", Variable))

thedf$Variable = c("Average # DUI Arrests",
              "Average White DUI Rate (%)",
               "Average Black DUI Rate (%)",
               "Average # Fatal Crashes",
               "Average # Crash Fatalities",
              "Average Unemployment Rate (%)",
              "Average Per Capita Income ($)",
              "Average % of Population 65+")

thedf %>%
  kbl(caption = "Descriptive Statistics", booktabs = T) %>%
  kable_styling(latex_options = c("hold_position")) %>%
  pack_rows("UCR Variables", 1, 3) %>%
  pack_rows("FARS Variables", 4, 5) %>%
  pack_rows("Controls", 6, 8)



```






Data sources:

* [State Unemployment Rates](https://www.icip.iastate.edu/tables/employment/unemployment-states)
* [State per capita income](https://apps.bea.gov/iTable/iTable.cfm?reqid=70&step=1&acrdn=2)
