---
title: "County Level FARS"
author: "Blain Morin"
date: "4/20/2022"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(lubridate)
library(readr)
library(plotly)
library(ggridges)
library(stargazer)
library(data.table) 
library(fixest) 
library(broom)
library(haven)
library(readxl)
library(bacondecomp)
library(did)

```

# Notes:

* Here I've repeated the FARS data analysis at the county level




# Outcome: Fatal Crash Rate

```{r}

### Read in FARS data
fars = read_dta("FARS19752016_clean.dta")

### Get state identifiers to attach to FARS
state.id = read_csv("accident.CSV") %>% # Read in csv
  select(STATE, STATENAME) %>% # then select state id and state name columns
  group_by(STATENAME) %>% # then group by state
  slice(1) %>% # then grab one observation
  mutate(STATENAME = tolower(STATENAME)) %>% # then make the state names lowercase
  rename(state = STATE) # then rename the state column to lowercase too

### Create dummy variable for MJ Detected
fars = fars %>%
  mutate(mj = ifelse(drugid1 == 605, 1, 0)) # 605 is MJ


fars2 = fars %>%
  select(state, county, month, crashid,
         numaccfats, vehdrdrive, drugs, race, mj) %>% # select these columns
  mutate(year = substr(crashid, 1, 4)) %>% # then create year from accident identifier
  mutate(year = as.numeric(year)) %>% # then make year numeric
  left_join(state.id) %>% # then attach state names
  group_by(year, STATENAME, county) %>% # then group by year county and state
  summarise(drunk.drive = sum(vehdrdrive, na.rm = TRUE), # calculate sums of these events
            drug.drive = sum(drugs, na.rm = TRUE),
            mj.drive = sum(mj, na.rm = TRUE)) %>%
  rename(state = STATENAME, fips_county_code = county) %>% # clean up column names
  mutate(fips_county_code = str_pad(fips_county_code, 3,
                                    side = "left", pad = "0")) # Add 0 to FIPS codes

fars3 = fars %>%
  select(state, county, month, crashid, numaccfats, vehdrdrive, drugs, race) %>%
  mutate(year = substr(crashid, 1, 4)) %>%
  mutate(year = as.numeric(year)) %>%
  left_join(state.id) %>%
  group_by(year, STATENAME, crashid) %>% # group by crash id
  slice(1) %>% # and take one observation (avoids double counting)
  ungroup() %>%
  group_by(year, STATENAME, county) %>%
  summarise(fatals = sum(numaccfats),
            n_crashes = n()) %>%
  rename(state = STATENAME, fips_county_code = county) %>%
  mutate(fips_county_code = str_pad(fips_county_code, 3, side = "left", pad = "0"))

county.fars = fars2 %>%
  left_join(fars3) %>%
  drop_na(fips_county_code)

county.fars = county.fars %>%
  mutate(treatdate = ifelse(state == "rhode island", "July 1989", NA)) %>%
  mutate(treatdate = ifelse(state == "washington", "May 1988", treatdate)) %>%
  mutate(treatdate = ifelse(state == "wisconsin", "Aug 1991", treatdate)) %>%
  mutate(treatdate = ifelse(state == "texas", "June 1994", treatdate)) %>%
  mutate(treatdate = ifelse(state == "idaho", "June 1988", treatdate)) %>%
  mutate(treatdate = ifelse(state == "iowa", "May 1986", treatdate)) %>%
  mutate(treatdate = ifelse(state == "michigan", "Sep 1993", treatdate)) %>%
  mutate(treatdate = ifelse(state == "minnesota", "Aug 1994", treatdate)) %>%
  mutate(treatdate = ifelse(state == "oregon", "Sep 1987", treatdate)) %>%
  mutate(treatdate = my(treatdate)) %>%
  mutate(treatyear = format(treatdate, format = "%Y"))

### Declare treated states
treated_states = c("washington", "wisconsin",
                   "rhode island", "texas",
                   "idaho", "iowa",
                   "michigan", "minnesota",
                   "oregon")

county.fars = county.fars %>%
  ### Make the time to treat column
  mutate(timetotreat = as.numeric(year) - as.numeric(treatyear)) %>%
  ### Make indicator for treated state
  mutate(treated = ifelse(state %in% treated_states, 1, 0)) %>%
  ### Make years discrete
  mutate(fyear = as.factor(year)) 

countypop = read_dta("countypopagerace_19692017.dta") %>%
  group_by(year, stfips, cofips) %>%
  summarise(co.population = sum(population, na.rm = TRUE)) %>%
  rename(fips_county_code = cofips) %>%
  mutate(fips_county_code = str_pad(fips_county_code, 3, side = "left", pad = "0")) %>%
  mutate(stfips = as.character(stfips))

countypopbyrace = read_dta("countypopagerace_19692017.dta") %>%
  group_by(year, stfips, cofips, race) %>%
  summarise(racepop = sum(population)) %>%
  rename(fips_county_code = cofips) %>%
  mutate(fips_county_code = str_pad(fips_county_code, 3, side = "left", pad = "0")) %>%
  mutate(stfips = as.character(stfips))

fips.appendage = state.id %>%
  rename(stfips = state) %>%
  rename(state = STATENAME) %>%
  mutate(stfips = as.character(stfips))

county.fars = county.fars %>%
  left_join(fips.appendage) %>%
  left_join(countypop) %>%
  left_join(countypopbyrace) %>%
  mutate(stfips = str_pad(as.character(stfips), 2, side = "left", pad = "0")) %>%
  mutate(fips = paste0(stfips, fips_county_code))

county.fars = county.fars %>%
  filter(year %in% 1980:2000) %>%
  mutate(timetotreat = replace_na(timetotreat, 0)) %>%
  mutate(post = ifelse(timetotreat > 0, 1, 0)) %>%
  rename(treated_blain = treated) %>%
  filter(!fips_county_code %in%  c("000", "999"))

county.fars = county.fars %>%
  ungroup() %>%
  mutate(gname = replace_na(as.numeric(county.fars$treatyear), 0)) %>%
  mutate(gname = ifelse(gname == 1976, 0, gname)) %>%
  mutate(id.numeric = as.numeric(as.factor(fips))) %>%
  drop_na(co.population) 

county.fars.appendage = county.fars %>%
  group_by(year, stfips, fips_county_code) %>%
  summarise(n_obs = n()) %>%
  ungroup()
  
county.fars = county.fars %>%
  left_join(county.fars.appendage) %>%
  filter(n_obs == 3)

```

```{r, fig.height=14}

county.fars %>%
  filter(race == 2) %>%
  mutate(prop.black = racepop / co.population) %>%
  mutate(fatal.rate = fatals / co.population) %>%
  ggplot(aes(x = log(prop.black), y = log(fatal.rate))) +
  geom_point() +
  facet_wrap(~state, ncol = 4) +
  theme_classic() +
  geom_smooth(method = "lm", se = FALSE)

```