---
title: "Year Arrests, FERC Data"
author: "Blain Morin"
date: "1/25/2022"
output: html_document
---

# Recap

* Redo arrest analysis using +-6 years, instead of using +-12 months

* Run the analysis using FARS crash data

# Arrests

* Drop Wyoming because of the lower bound of arrest data (Wyoming ends in 1975 and arrests data starts at 1974)
  * Maybe model can work with the cutoff, but need to think on it



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, cache = TRUE)

library(tidyverse)
library(lubridate)
library(readr)
library(plotly)
library(ggridges)
library(stargazer)
library(data.table) 
library(fixest) 

```


```{r}

states = c("WA", "WI", "RI", "OH", "TX", "ID", "IA", "MI", "MN", "OR")
treated_states = c("washington", "wisconsin", "rhode island", "texas",
                   "wyoming", "idaho", "iowa",
                   "michigan", "minnesota",
                   "oregon")

df = data.frame()

for (i in 1974:2020) {
  
  filename = paste0("~/michigan_arrests/data/ucr_arrests_monthly_all_crimes_race_sex_", i, ".rds")
  
  temp = readRDS(filename) %>%
    select(fips_county_code, state, agency_name, year, month, starts_with("dui"))
  
  df = rbind(df, temp)
  
}


df.sum = df %>%
  mutate(monthyear = paste(month, year)) %>%
  mutate(d = my(monthyear)) %>%
  group_by(year, state) %>%
  summarise(DUI_Total = sum(dui_tot_arrests),
            DUI_p.Black = sum(dui_tot_black) / sum(dui_tot_arrests)) %>%
  ungroup()

df.sum = df.sum %>%
  mutate(treatdate = ifelse(state == "rhode island", "July 1989", NA)) %>%
  mutate(treatdate = ifelse(state == "washington", "May 1988", treatdate)) %>%
  mutate(treatdate = ifelse(state == "wisconsin", "Aug 1991", treatdate)) %>%
  mutate(treatdate = ifelse(state == "texas", "June 1994", treatdate)) %>%
  mutate(treatdate = ifelse(state == "idaho", "June 1988", treatdate)) %>%
  mutate(treatdate = ifelse(state == "iowa", "May 1986", treatdate)) %>%
  mutate(treatdate = ifelse(state == "michigan", "Sep 1993", treatdate)) %>%
  mutate(treatdate = ifelse(state == "minnesota", "Aug 1994", treatdate)) %>%
  mutate(treatdate = ifelse(state == "oregon", "Sep 1987", treatdate)) %>%
  mutate(treatdate = my(treatdate)) %>%
  mutate(treatyear = format(treatdate, format = "%Y"))

df.sum = df.sum %>%
  mutate(timetotreat = as.numeric(year) - as.numeric(treatyear)) %>%
  mutate(treated = ifelse(state %in% treated_states, 1, 0)) %>%
  mutate(fyear = as.factor(year)) %>%
  mutate(timetotreat = replace_na(timetotreat, 0)) %>%
  mutate(treated = replace_na(treated, 0))

```

