---
title: "All Event Studies"
author: "Blain Morin"
date: "4/6/2022"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(lubridate)
library(readr)
library(plotly)
library(ggridges)
library(stargazer)
library(data.table) 
library(fixest) 
library(haven)
library(kableExtra)
library(readxl)
library(gridExtra)
library(did)
library(bacondecomp)

```

```{r}

# ###################################
# ### Uniform Crime Reporting (UCR)
# ###################################
# 
# ### Initialize a dataframe
# df = data.frame()
# 
# ### The UCR data is broken into years
# ### This for loop cycles through the declared years and
# ### concatenates them (flattens to one dataframe)
# 
# ### 1980 to 2000 captures 6 years before first treatment
# ### And 6 years after last treatment
# for (i in 1991:2000) {
#   
#   filename = paste0("~/michigan_arrests/data/ucr_arrests_monthly_all_crimes_race_sex_", i, ".rds")
#   
#   ### Here the variables from UCR data are selected
#   temp = readRDS(filename) %>% 
#     select(fips_county_code,
#            state, population, 
#            agency_name, year,
#            month,
#            starts_with("dui"),
#            number_of_months_reported,
#            starts_with("poss_cannabis"),
#            starts_with("poss_drug_total"),
#            starts_with("drunkenness"),
#            starts_with("disorder_cond"),
#            starts_with("curfew_loiter"),
#            starts_with("vagrancy"),
#            starts_with("suspicion"),
#            starts_with("total_drug")
#            )
#   
#   df = rbind(df, temp)
#   
# }
# 
# 
# 
# 
# ### Here I group by year and state and
# ### calculate the total DUI 
# df.sum = df %>%
#   group_by(year, state) %>%
#   summarise(DUI_Total = sum(dui_tot_arrests),
#             DUI_Total_Black = sum(dui_tot_black),
#             
#             Poss_Cann_Total = sum(poss_cannabis_tot_arrests),
#             Poss_Cann_Total_Black = sum(poss_cannabis_tot_black),
#             
#             Poss_Drug_Total = sum(poss_drug_total_tot_arrests),
#             Poss_Drug_Total_Black = sum(poss_drug_total_tot_black),
#             
#             Disorderly_Total = sum(disorder_cond_tot_arrests),
#             Disorderly_Total_Black = sum(disorder_cond_tot_black),
#             
#             Drunkenness_Total = sum(drunkenness_tot_arrests),
#             Drunkenness_Total_Black = sum(drunkenness_tot_black),
#             
#             Loitering_Total = sum(curfew_loiter_tot_arrests),
#             Loitering_Total_Black = sum(curfew_loiter_tot_black),
#             
#             Vagrancy_Total = sum(vagrancy_tot_arrests),
#             Vagrancy_Total_Black = sum(vagrancy_tot_black),
#             
#             Suspicion_Total = sum(suspicion_tot_arrests),
#             Suspicion_Total_Black = sum(suspicion_tot_black)
#             
#             ) %>%
#   ungroup()
# 
# 
# write.csv(df.sum, file = "temp2.csv", row.names = FALSE)

temp1 = read_csv("temp1.csv")
temp2 = read_csv("temp2.csv")

df.sum = rbind(temp1, temp2)


### Here I attach the treatment date to the 
### corresponding state
df.sum = df.sum %>%
  mutate(treatdate = ifelse(state == "rhode island", "July 1989", NA)) %>%
  mutate(treatdate = ifelse(state == "washington", "May 1988", treatdate)) %>%
  mutate(treatdate = ifelse(state == "wisconsin", "Aug 1991", treatdate)) %>%
  mutate(treatdate = ifelse(state == "texas", "June 1994", treatdate)) %>%
  mutate(treatdate = ifelse(state == "idaho", "June 1988", treatdate)) %>%
  mutate(treatdate = ifelse(state == "iowa", "May 1986", treatdate)) %>%
  mutate(treatdate = ifelse(state == "michigan", "Sep 1993", treatdate)) %>%
  mutate(treatdate = ifelse(state == "minnesota", "Aug 1994", treatdate)) %>%
  mutate(treatdate = ifelse(state == "oregon", "Sep 1987", treatdate)) %>%
  ### Although the month is declared above, we only use the treatyear
  mutate(treatdate = my(treatdate)) %>%
  mutate(treatyear = format(treatdate, format = "%Y"))

### Declare treated states
treated_states = c("washington", "wisconsin", "rhode island", "texas", "idaho", "iowa",
                   "michigan", "minnesota",
                   "oregon")

df.sum = df.sum %>%
  ### Make the time to treat column
  mutate(timetotreat = as.numeric(year) - as.numeric(treatyear)) %>%
  ### Make indicator for treated state
  mutate(treated = ifelse(state %in% treated_states, 1, 0)) %>%
  ### Make years discrete
  mutate(fyear = as.factor(year)) 


### These are some non-states that are dropped from the analysis
nonstate = c("canal zone", "guam", "69", "98", "99", "american samoa", "virgin islands", "puerto rico")

### This filters out the non-states
df2 = df.sum %>%
  filter(!state %in% nonstate)

### Attach state weights
### Read in the file
state_populations = read_excel("laws and population.xlsx")

### Select relevant columns
state_populations = state_populations %>%
  select(`state name`, year, `population (hundreds of thousands)`)

### Rename and clean some columns so that they will join to 
### our UCR and FARS data
state_populations = state_populations %>%
  rename(state = `state name`) %>%
  rename(population = `population (hundreds of thousands)`) %>%
  mutate(state = tolower(state))

df3 = df2 %>%
  left_join(state_populations) %>%
  drop_na(population) 

df3 = df3 %>%
  mutate(timetotreat = replace_na(df3$timetotreat, 0)) %>%
  mutate(post = ifelse(timetotreat > 0, 1, 0)) %>%
  rename(treated_alt = treated) %>% # Change treated name to be friendly with 'did' package
  
  mutate(DUI_Rate = DUI_Total / population) %>%
  mutate(DUI_Rate_Black = DUI_Total_Black / population) %>%
  
  mutate(Poss_Cann_Rate = Poss_Cann_Total / population) %>%
  mutate(Poss_Cann_Rate_Black = Poss_Cann_Total_Black / population) %>%
  
  mutate(Poss_Drug_Rate = Poss_Drug_Total / population) %>%
  mutate(Poss_Drug_Rate_Black = Poss_Drug_Total_Black / population) %>%
  
  mutate(Disorderly_Rate = Disorderly_Total / population) %>%
  mutate(Disorderly_Rate_Black = Disorderly_Total_Black / population) %>%
  
  mutate(Drunkenness_Rate = Drunkenness_Total / population) %>%
  mutate(Drunkenness_Rate_Black = Drunkenness_Total_Black / population) %>%
  
  mutate(Loitering_Rate = Loitering_Total / population) %>%
  mutate(Loitering_Rate_Black = Loitering_Total_Black / population) %>%
  
  mutate(Vagrancy_Rate = Vagrancy_Total / population) %>%
  mutate(Vagrancy_Rate_Black = Vagrancy_Total_Black / population) %>%
  
  mutate(Suspicion_Rate = Suspicion_Total / population) %>%
  mutate(Suspicion_Rate_Black = Suspicion_Total_Black / population)

df3 = df3 %>%
  mutate(gname = replace_na(as.numeric(df3$treatyear), 0)) %>%
  mutate(id.numeric = as.numeric(as.factor(state)))

```


```{r}

cs.model = att_gt(
  yname = "DUI_Total",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Drunk Drive Arrests")


```

```{r}

cs.model = att_gt(
  yname = "DUI_Total_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Drunk Drive Arrests")


```

```{r}

cs.model = att_gt(
  yname = "DUI_Rate",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Drunk Drive Rate")


```

```{r}

cs.model = att_gt(
  yname = "DUI_Rate_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Drunk Drive Rate")


```

```{r}

cs.model = att_gt(
  yname = "Poss_Cann_Total",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Cannabis Possesion Arrests")


```

```{r}

cs.model = att_gt(
  yname = "Poss_Cann_Total_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Cannabis Possesion Arrests")


```


```{r}

cs.model = att_gt(
  yname = "Poss_Cann_Rate",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Cannabis Possesion Rate")


```

```{r}

cs.model = att_gt(
  yname = "Poss_Cann_Rate_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Cannabis Possesion Rate")


```

```{r}

cs.model = att_gt(
  yname = "Poss_Drug_Total",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Drug Possesion Arrests")


```

```{r}

cs.model = att_gt(
  yname = "Poss_Drug_Total_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Drug Possesion Arrests")


```

```{r}

cs.model = att_gt(
  yname = "Poss_Drug_Rate",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Drug Possesion Rate")


```

```{r}

cs.model = att_gt(
  yname = "Poss_Drug_Rate_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Drug Possesion Rate")


```

```{r}

cs.model = att_gt(
  yname = "Disorderly_Total",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Disorderly Arrests")


```

```{r}

cs.model = att_gt(
  yname = "Disorderly_Total_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Disorderly Arrests")


```

```{r}

cs.model = att_gt(
  yname = "Disorderly_Rate",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Disorderly Rate")


```

```{r}

cs.model = att_gt(
  yname = "Disorderly_Rate_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Disorderly Rate")


```

```{r}

cs.model = att_gt(
  yname = "Drunkenness_Total",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Drunkenness Arrests")


```

```{r}

cs.model = att_gt(
  yname = "Drunkenness_Total_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Drunkenness Arrests")


```

```{r}

cs.model = att_gt(
  yname = "Drunkenness_Rate",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Drunkenness Rate")


```

```{r}

cs.model = att_gt(
  yname = "Drunkenness_Rate_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Drunkenness Rate")


```

```{r}

cs.model = att_gt(
  yname = "Loitering_Total",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Loitering Arrests")


```

```{r}

cs.model = att_gt(
  yname = "Loitering_Total_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Loitering Arrests")


```

```{r}

cs.model = att_gt(
  yname = "Loitering_Rate",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Loitering Rate")


```

```{r}

cs.model = att_gt(
  yname = "Loitering_Rate_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Loitering Rate")


```

```{r}

cs.model = att_gt(
  yname = "Vagrancy_Total",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Vagrancy Arrests")


```

```{r}

cs.model = att_gt(
  yname = "Vagrancy_Total_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Vagrancy Arrests")


```

```{r}

cs.model = att_gt(
  yname = "Vagrancy_Rate",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Vagrancy Rate")


```

```{r}

cs.model = att_gt(
  yname = "Vagrancy_Rate_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Vagrancy Rate")


```

```{r}

cs.model = att_gt(
  yname = "Suspicion_Total",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Suspicion Arrests")


```

```{r}

cs.model = att_gt(
  yname = "Suspicion_Total_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Suspicion Arrests")


```

```{r}

cs.model = att_gt(
  yname = "Suspicion_Rate",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Total Suspicion Rate")


```

```{r}

cs.model = att_gt(
  yname = "Suspicion_Rate_Black",
  tname = "year",
  idname = "id.numeric",
  gname = "gname",
  weightsname = "population",
  data = df3
)

dyn.cs.model = aggte(cs.model, type = "dynamic")

ggdid(dyn.cs.model) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Black Suspicion Rate")


```

